name: CI-Pipeline

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:

  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build and Run Tests with Maven
        run: mvn clean test

  integration_test:
    runs-on: ubuntu-latest
    needs: unit_test
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        run: git clone https://github.com/MiguelCastilloSanchez/spring-boot-posts-service.git
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build and Run Tests with Maven
        run: mvn clean test -Dtest=ProjectScannerServiceTest

  formatting:
    runs-on: ubuntu-latest
    needs: integration_test
    steps:
      - uses: actions/checkout@v4
      - uses: axel-op/googlejavaformat-action@v4
        with:
          args: "--skip-sorting-imports --replace"
      - name: Commit and Push if Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Apply Java formatting"
          git push